name: marvel_vrsoft
description: A new Flutter project. Created by Slidy

publish_to: 'none'
version: 1.0.0+1

## Slidy Scripts 
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    mobx_build: $runner build
    mobx_watch: $clean & $get & $runner watch
    mobx_build_clean: $clean & $get & $runner build --delete-conflicting-outputs



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  local_auth: ^0.6.3+4
  font_awesome_flutter: ^8.11.0
  shared_preferences: ^0.5.12+4
  avatar_glow: ^1.2.0
  http: ^0.12.2
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9
  firebase_core : ^0.7.0
  flutter_modular: ^2.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  mockito:
  modular_codegen:
  mobx_codegen: ^1.1.2
  build_runner: ^1.10.1
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/img/ic_marvel.png"
  image_path_android: "lib/img/ic_marvel.png"

flutter:

  uses-material-design: true

  assets:
    - lib/img/marvel_logo.png
    - lib/img/ic_marvel.png
